"""Add priority field to jobs

Revision ID: 85e85164e7b2
Revises: 288611d616c1
Create Date: 2026-01-30 16:29:34.132101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e85164e7b2'
down_revision: Union[str, None] = '288611d616c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('priority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'priority')
    # ### end Alembic commands ###
