"""Add scheduled at field

Revision ID: b971cc333cde
Revises: 85e85164e7b2
Create Date: 2026-01-30 16:43:38.438755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b971cc333cde'
down_revision: Union[str, None] = '85e85164e7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'scheduled_at')
    # ### end Alembic commands ###
